[build]
  publish = "dist"
  command = "npm run build"

[functions]
  # If you have functions, specify the directory here
  # directory = "netlify/functions"

# Headers configuration
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/partytown/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"

# Redirects configuration (example)
# [[redirects]]
  # from = "/old-path"
  # to = "/new-path"
  # status = 301
  # force = true

[[redirects]]
  from = "/~partytown/*"
  to = "/_astro/partytown/:splat"
  status = 200

# Environment variables (if needed)
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-sitemap"