[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  # If you have functions, specify the directory here
  # directory = "netlify/functions"

# Headers configuration
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects configuration (example)
# [[redirects]]
  # from = "/old-path"
  # to = "/new-path"
  # status = 301
  # force = true

# Environment variables (if needed)
[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Set minimum thresholds for each report area
  [plugins.inputs.thresholds]
    performance = 0.9

  # to audit a path other than /
  # route1 audit will use the top level thresholds
  #[[plugins.inputs.audits]]
  #  path = "route1"

  # you can optionally specify an output_path per audit, relative to the path, where HTML report output will be saved
    output_path = "reports/route1.html"

  # to audit a specific absolute url
  [[plugins.inputs.audits]]
    url = "https://tale-of-survival.netlify.app"

    # you can specify thresholds per audit
    [plugins.inputs.audits.thresholds]
      performance = 0.8