[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  # If you have functions, specify the directory here
  # directory = "netlify/functions"

# Headers configuration
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects configuration (example)
# [[redirects]]
  # from = "/old-path"
  # to = "/new-path"
  # status = 301
  # force = true

# Environment variables (if needed)
[build.environment]
  NODE_ENV = "production"